// <auto-generated />
namespace LawnBattle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Moremodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Moremodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201405261402549_More models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
