// <auto-generated />
namespace LawnBattle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedgamestotourny : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedgamestotourny));
        
        string IMigrationMetadata.Id
        {
            get { return "201405290715488_added games to tourny"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
